feat: add custom cursor
starknet-id/starknet.quest pull request #351
Opened 2023-11-20 09:22 UTC by ayushtom

closes #206

2023-11-22 17:40 UTC, ayushtom commented on styles/achievements.module.css
> +  background: linear-gradient(90deg,
yes. Can you dm me your config files? I'll replace them in my editor

2023-11-23 08:52 UTC, irisdv requested changes
Looks good ! Just, are you using the svg files for the cursor ?

2023-11-23 11:12 UTC, ayushtom commented
removed extra svg files

2023-11-23 11:26 UTC, irisdv approved these changes
lgtm

2023-11-23 11:26 UTC, merged