feat: mobile screen redesign
starknet-id/starknet.quest pull request #425
Opened 2023-12-16 15:01 UTC by Marchand-Nicolas

close: #404 
close: #403

2023-12-27 12:34 UTC, Kevils requested changes
1 - There is a slight pixel offset when opening the menu between the logo and the close icon compared to the original ones. Can we fix that? It seems to me that this also happens on Starknet ID

2 - Add more margin (container) on this text(Partnership, 16px left and right
<img width="466" alt="Screenshot 2023-12-27 at 11 46 54" src="https://github.com/starknet-id/starknet.quest/assets/144677881/aefaed39-27e1-48ed-ac6f-87dee2a76acb">

2023-12-27 13:41 UTC, Marchand-Nicolas commented
> 1 - There is a slight pixel offset when opening the menu between the logo and the close icon compared to the original ones. Can we fix that? It seems to me that this also happens on Starknet ID

I will do PRs to fix that on Starknet ID

2023-12-27 14:08 UTC, Marchand-Nicolas commented
https://github.com/starknet-id/starknet.id/pull/50
https://github.com/starknet-id/app.starknet.id/pull/607

2023-12-27 14:42 UTC, Kevils approved these changes
Lgtm

2023-12-28 22:29 UTC, ayushtom commented on components/UI/navbar.tsx
> +                <div className="rounded-full shadow-gray-400 p-3 modified-cursor-pointer hover:scale-105 ease-in duration-300 mt-6">
should we add this styling in a css class and add it here? seems to be repeated in two places. Would be easier to modify both at once next time from one place

2023-12-28 22:29 UTC, ayushtom commented on components/lands/scene.tsx
> +      if (window.innerWidth < 768) return;
in css files we consider mobile as 740px and here 768px. They should have the same value for mobile no?

2023-12-29 14:46 UTC, ayushtom commented
lgtm

2023-12-29 14:47 UTC, ayushtom approved these changes

2023-12-29 14:47 UTC, merged