update: added check to handle error
starknet-id/starknet.quest pull request #571
Opened 2024-03-31 10:08 UTC by raizo07

# Pull Request type

Added a check to avoid the errors related to trying to access properties of an undefined or null `data` object.

Also added a check for `data` before attempting to access the 'error' property to prevent the TypeError.

2024-04-01 07:35 UTC, ayushtom commented
closes #559

2024-04-03 16:56 UTC, fricoben requested changes
The bug is not fixed. 

To reproduce the bug you simply have to:
- [ ] Visit https://starknet.quest/quest/107
<img width="389" alt="Capture d’écran 2024-04-03 à 13 56 41" src="https://github.com/starknet-id/starknet.quest/assets/78437165/a3093d7e-5c13-4523-9f9d-9388d57dca1f">

- [ ] Connect to *Argent Web Wallet* (by Email)

2024-04-03 16:56 UTC, fricoben commented on context/QuestsProvider.tsx
> +    }
The error is not here but in the `[questPage]` part

To delete

2024-04-03 16:56 UTC, fricoben commented on context/QuestsProvider.tsx
> +        if (data && (data as QueryError).error) return; // Check if 'data' exists before accessing 'error'
The error is not here but in the `[questPage]` part

To delete

2024-04-05 17:59 UTC, ayushtom commented
@raizo07 could you fix this? i think we will have to reassign if this soon if you haven't been able to fix this yet

2024-04-05 18:11 UTC, raizo07 commented
I just got some pointers from @Fricoben and I'm working on it already.

On Fri, 5 Apr 2024, 19:00 Ayush Tomar, ***@***.***> wrote:

> @raizo07 <https://github.com/raizo07> could you fix this? i think we will
> have to reassign if this soon if you haven't been able to fix this yet
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/starknet-id/starknet.quest/pull/571#issuecomment-2040349472>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATKSYSQMPXVDB6SJYQ3MWHLY33RCBAVCNFSM6AAAAABFQJJIVGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBQGM2DSNBXGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-08 08:58 UTC, ayushtom commented
@raizo07 i am unassigning this issue from you. This has taken a long time and i dont see much progress. You can continue to work and fix this but this won't be considered for your OD rewards.

2024-04-16 12:02 UTC, ayushtom commented
this pr is not fixing the issue as of now so closing

2024-04-16 12:02 UTC, closed without merging