chore: add test cases for getTaskByQuestId service
starknet-id/starknet.quest pull request #629
Opened 2024-04-23 09:54 UTC by leevigh

I changed the apiService.test.js file to test the getTasksByQuestId API service. The test included checks for:
- when API returns no response
- when API returns a response in an unexpected format
- case when endpoint values are undefined and null
- when response is successful

# Pull Request type
chore: add test case

Please add the labels corresponding to the type of changes your PR introduces: Testing.
- Testing

Resolves: #619

2024-04-25 07:21 UTC, ayushtom commented on tests/services/apiService.test.js
> +    let result = await getTasksByQuestId({ address: '2' })
the result here are error strings which the api returns. Not undefined. I would suggest you to test these values in the api and then check if the mock returns you have added here are correct

2024-04-25 07:21 UTC, ayushtom commented on tests/services/apiService.test.js
> +      {
not a valid mock data response. Please confirm with api what you get here

2024-04-25 12:06 UTC, ayushtom commented
can you please resolve conflicts?

2024-04-25 12:53 UTC, leevigh commented
> can you please resolve conflicts?

I'm done resolving the conflicts

2024-04-26 05:33 UTC, ayushtom approved these changes
test cases lgtm

2024-04-26 05:35 UTC, ayushtom commented
can you please upload the test command output so i can verify if this covers the api call you were assigned

2024-04-26 05:37 UTC, ayushtom requested changes
you need to also add the typings of the response format on the front like i mention in the issue

2024-04-26 09:30 UTC, leevigh commented
> can you please upload the test command output so i can verify if this covers the api call you were assigned

My tests cover lines 239-255 of apiService.ts


![Screenshot 2024-04-26 at 10 05 48](https://github.com/starknet-id/starknet.quest/assets/29841388/262a1db3-d49d-461a-951d-dcc3de623679)

2024-04-26 09:52 UTC, leevigh commented
> you need to also add the typings of the response format on the front like i mention in the issue

The types are included in the getTasksByQuestId service response data i.e UserTask[] | QueryError. 
Could you please clarify what typings you are referring to in case I have misunderstood it?

2024-04-27 08:31 UTC, ayushtom approved these changes
lgtm

2024-04-27 08:32 UTC, merged