test: get_quests
starknet-id/starknet.quest pull request #635
Opened 2024-04-23 15:38 UTC by Iwueseiter

# Pull Request type

Test

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #618

2024-04-25 07:37 UTC, ayushtom commented on tests/services/getQuests.test.js
> +    const mockData = [
i dont think this a valid returned data. Can you please test the endpoint for this and add that data here for verification. You will also need to add it as a return type in the api call in apiServices.ts

2024-04-25 07:37 UTC, ayushtom commented on tests/services/getQuests.test.js
> +import { getQuests } from "@services/apiService";
add in apiService.test.js

2024-04-27 08:40 UTC, ayushtom commented
can you also move your test cases to apiServices.test.js file like others?
i also mention this here - https://github.com/starknet-id/starknet.quest/pull/635#discussion_r1579020566

2024-04-29 10:13 UTC, ayushtom commented on services/apiService.ts
> +export const getQuests = async (): Promise<object | undefined> => {
i think return type here is not this. Something like {[string]:QuestDocument[]}

2024-04-30 08:02 UTC, ayushtom commented
@Iwueseiter i will be assigning someone else to finish this PR today. If you can then please commit the changes here so i can review and merge or else we give it to someone who can close the issue

2024-04-30 15:39 UTC, Iwueseiter commented
@ayushtom I've effected the changes

2024-04-30 22:48 UTC, ayushtom commented
@Iwueseiter your build is failing

2024-04-30 23:28 UTC, ayushtom commented on services/apiService.ts
> +export const getQuests = async (): Promise<QuestDocument | undefined> => {
QuestDocument | QueryError can be useful here

2024-05-01 18:43 UTC, ayushtom commented
@Iwueseiter your build is failing

2024-05-03 17:35 UTC, ayushtom requested changes

2024-05-03 17:35 UTC, ayushtom commented on types/backTypes.d.ts
> +type GetQuestsRes =
can you rename this as `QuestsList`

2024-05-03 17:35 UTC, ayushtom commented on services/apiService.ts
> +export const getQuests = async (): Promise<GetQuestsRes | undefined> => {
QueryError instead of undefined

2024-05-03 17:35 UTC, ayushtom commented on context/QuestsProvider.tsx
> +      if (data) {
`if (!data || "error" in res) return;`

// add code of if block below

can work here when you add QueryError instead of undefined

2024-05-03 17:35 UTC, ayushtom commented
also please resolve conflicts

2024-05-11 09:14 UTC, ayushtom approved these changes
lgtm

2024-05-11 09:15 UTC, merged