unit tests for get_quest_participations
starknet-id/starknet.quest pull request #648
Opened 2024-04-25 16:43 UTC by muheebyusufbaba1

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #604

## Other information

2024-04-26 05:46 UTC, ayushtom reviewed
can you also add response format in the return type of the api call so we can consume those typings on the front

2024-04-29 17:34 UTC, muheebyusufbaba1 commented
@ayushtom

2024-04-29 20:11 UTC, ayushtom commented
@muheebyusufbaba1 you have build issues
you can check the issue locally by running npm run build and seeing what is the issue and fix it
once done i think your PR is good to go for merge

2024-04-30 08:02 UTC, ayushtom commented
@muheebyusufbaba1  i will be assigning someone else to finish this PR today. If you can then please commit the changes here so i can review and merge or else we give it to someone who can close the issue

2024-04-30 08:04 UTC, muheebyusufbaba1 commented
I'll do this right away, working on it

2024-04-30 09:40 UTC, ayushtom requested changes

2024-04-30 09:40 UTC, ayushtom commented on app/quest-boost/[boostId]/page.tsx
> +          const res = (await getQuestParticipants(questID)) as QuestParticipantsDocument;
is this type hardcoding really required

2024-04-30 09:45 UTC, muheebyusufbaba1 commented on app/quest-boost/[boostId]/page.tsx
> +          const res = (await getQuestParticipants(questID)) as QuestParticipantsDocument;
Build is failing when I take it out

2024-04-30 09:50 UTC, ayushtom commented on app/quest-boost/[boostId]/page.tsx
> +          const res = (await getQuestParticipants(questID)) as QuestParticipantsDocument;
got it

2024-04-30 10:01 UTC, ayushtom approved these changes
lgtm

2024-04-30 10:01 UTC, merged