Feat/view quests to claim rewards
starknet-id/starknet.quest pull request #686
Opened 2024-05-09 15:46 UTC by Ayoazeez26

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Testing

Resolves: #595

## Other information

2024-05-09 17:55 UTC, ayushtom commented
Initial review - 
- dont show to claim tab if wallet is not connected
- navigate to `/quest-boost/5` which is the boost page for quest id 23. If i click on claim reward or the card too.

2024-05-09 21:11 UTC, Ayoazeez26 commented
> * navigate to `/quest-boost/5` which is the boost page for quest id 23. If i click on claim reward or the card too.

@ayushtom I believe this is the current implemented behaviour, correct me if I'm wrong.

2024-05-11 09:06 UTC, ayushtom requested changes

2024-05-11 09:06 UTC, ayushtom commented on utils/quest.ts
> +  if (pendingBoostClaims && pendingBoostClaims.length) {
can write this as 
if(!pendingBoostClaims) return;
// rest of the code

helps with avoiding nested standalone if blocks

2024-05-14 09:56 UTC, ayushtom approved these changes
lgtm

2024-05-14 09:56 UTC, merged