Feat/add bitget wallet support
starknet-id/starknet.quest pull request #915
Opened 2024-10-29 11:50 UTC by jaiminRaiyani

This PR introduces support for the Bitget wallet in the Starknet Quest application. This includes updates to components and hooks to facilitate Bitget wallet integration and make it available for user selection.

**Features :**

app/provider.tsx:
Added a new InjectedConnector instance for Bitget wallet, making it selectable from the available connectors list.

components/UI/changeWallet.tsx:
Modified wallet change functionality to include the Bitget wallet in relevant button displays.
Updated wallet selection conditions to recognize Bitget, ensuring it appears alongside existing wallets like Braavos and ArgentX.

components/UI/iconsComponents/icons/walletIcons.tsx:
Added an SVG icon for Bitget wallet, ensuring consistent UI representation within the app.

hooks/useGetDiscoveryWallets.ts:
Enhanced the useGetDiscoveryWallets hook to include Bitget wallet discovery and download link for easy access.

Resolves: #909 

## Other information
the svg icon for bitget might not work so do not consider that

2024-10-29 12:33 UTC, Marchand-Nicolas requested changes

2024-10-29 12:33 UTC, Marchand-Nicolas commented on components/UI/changeWallet.tsx
> +            ) {
@jaiminRaiyani this is a good suggestion https://github.com/lfglabs-dev/starknet.quest/pull/915/files#r1820659210

2024-10-29 16:26 UTC, jaiminRaiyani commented on components/UI/changeWallet.tsx
> +            ) {
@Marchand-Nicolas  i have implimented this suggestion you can review it

2024-10-29 21:12 UTC, Marchand-Nicolas commented
Hello @jaiminRaiyani Please resolve the conflicts

2024-10-29 21:23 UTC, Marchand-Nicolas approved these changes
Lgtm

2024-10-30 09:53 UTC, Marchand-Nicolas commented
@jaiminRaiyani Waiting for conflicts to be resolved in order to merge

2024-10-31 13:47 UTC, jaiminRaiyani commented
@Marchand-Nicolas  please review it i have resolved the conflict

2024-10-31 14:39 UTC, Marchand-Nicolas approved these changes
Lgtm :)

2024-10-31 14:39 UTC, merged