Change address of dashboard when changing wallets
starknet-id/starknet.quest pull request #941
Opened 2024-11-09 15:32 UTC by caxtonacollins

https://github.com/user-attachments/assets/7aff7db3-14d6-4a5e-a560-f2e29c48978a

2024-11-09 15:35 UTC, caxtonacollins commented
@kfastov please review

2024-11-10 02:11 UTC, kfastov commented
@caxtonacollins Sorry, was busy on HH, will review today

2024-11-10 07:29 UTC, fricoben requested changes
You got the overall idea, I propose you something way easier using starknet-react features

2024-11-10 07:29 UTC, fricoben commented on app/provider.tsx
> +                <WalletProvider>
I don't think you need a walletProvider here to do the job, it adds unnecessary complexity. 

What I would do instead is to use starknet react `useAccount()` hook to change URL based on the address you can get from it, you can do that directly on the `[addressOrDomain]/page.tsx` file. 

Here is an example of what i would look like. 

```tsx
export default function Page({ params }: AddressOrDomainProps) {
  // ... existing state declarations ...
  const [connectedAddress, setConnectedAddress] = useState<string | undefined>(); // address set as connected
  const { address } = useAccount(); // current address connected
  
  // Add this useEffect to handle address changes and URL updates
  useEffect(() => {    
    // Skip if the address hasn't changed or isn't defined
    if (!address || address === connectedAddress) return;
    
    // Update connected address state
    setConnectedAddress(address);
    
    // If we're not on the current user's profile, don't redirect
    if (address && addressOrDomain !== address && addressOrDomain !== undefined) {
      return;
    }
    
    // Redirect to the new address profile
    if (address) {
      router.push(`/${address}`);
    }
  }, [address, addressOrDomain, connectedAddress, router]);

  // ... rest of the component ...
}
```

I might have done some mistake here so I'll let you test and adapt but that solution would be way easier than adding a provider (starknet-react is your provider here)

2024-11-10 22:41 UTC, caxtonacollins commented
@fricoben please review

2024-11-11 06:13 UTC, fricoben requested changes
Need to fix conflcits and we're good

2024-11-12 06:20 UTC, fricoben commented
@caxtonacollins waiting for your conflicts fix

2024-11-12 13:10 UTC, caxtonacollins commented
@fricoben please review, conflicts resolved

2024-11-13 08:32 UTC, fricoben approved these changes

2024-11-13 08:35 UTC, merged